export default {
  GET_ALL_RANDOMALS: 'GET_ALL_RANDOMALS',
  GET_MY_RANDOMALS: 'GET_MY_RANDOMALS',
  DELETE_RANDOMAL: 'DELETE_RANDOMAL',
  ADD_RANDOMAL: 'ADD_RANDOMAL',
  RETURN_RANDOMALS: 'RETURN_RANDOMALS',
}
